### ISSUE TITLE
打开exe秒闪退

### ISSUE THREAD

**Issue by CHAKone** [Vita-314/AutoDownBUPDynamic#1]
大佬，我这打开exe就闪退怎么回事？联网正常，之前有次打开显示出二维码过，后面再也没办法正常打开出现登录二维码了。都是点击就秒没，没搞明白具体原因是啥导致的。

**Comment by Vita-314** [comment]
你好，已解决，重新下载新的包吧。
天，居然真的有人用啊。
原因是B站用了一种br类型响应请求，没做处理，所以不让他返回br类型了。另外多解决了个bug，就是如果动态文字有emoji表情在写入csv里会闪退，跳过处理了。

**Comment by CHAKone** [comment]
多谢大佬，大佬牛哇

**Comment by CHAKone** [comment]
大佬，发现新的问题。重新下载后的程序能够正常登陆运行，但是过了不到一分钟后就再次出现闪退和再次打开后闪退。重启电脑又可以打开运行一分钟左右闪，。下载内容正常，我打开log文件最后一条记录是下载成功然后没有其他的。大佬做的程序太契合我的需求和想法感谢大佬做的，也有可能是我电脑里的程序发生冲突，我看看如何测试下感谢辛苦大佬了。

**Comment by Vita-314** [comment]
加我q 72661784

**Comment by CHAKone** [comment]
好的，大佬QQ搜不到

**Comment by Vita-314** [comment]
点击链接加我为QQ好友：https://qm.qq.com/q/N7JTNItmUw

**Comment by Vita-314** [comment]
我去，我的问题，少打数字了
